repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        entry: hadolint
        language: system
        files: (^|/)(Dockerfile|.*\.Dockerfile)$
        args:
          - --ignore=DL3008
          - --ignore=DL3013

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
