name: Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: arc-runners-single-job
  cancel-in-progress: false

jobs:
  pre-commit:
    runs-on: arc-runners
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
